// -----------------------------------------------------------------------------
//  sprites.h - THE UI CHROME AND THE BODY LOOKUP. NOT AN ATLAS ANY MORE.
//
//  WHAT IS IN HERE: the 12x12 action icons, the 8x8 meter icons, the 12x12
//  genome badges, the twelve emotes, the SpritePose vocabulary, the flash
//  budget over all of the art, and - below the LOOKUP banner - the hand-written
//  logic that turns a Bug into a SpriteRef. All of it hand-typed, none of it
//  generated, and that is now stated once instead of being contradicted.
//
//  WHAT IS NOT: the creature art. `enum SpriteSetId`, `SPRITE_SETS` and the 38
//  Nottamagochi body and pose sets were deleted at P9-C3. The atlas is
//  data/sprites_bugs.h - 64 sets of 24x24x2, generated by tools/gen_sprites.py
//  from tools/sprites/*.txt, gated by `gen_sprites.py --check` in
//  tools/check.sh - and this file includes it.
//
//  THIS BANNER USED TO LIE, AND THE LIE IS WORTH KEEPING A PARAGRAPH FOR.
//  It said "GENERATED FILE - DO NOT HAND EDIT. Source of truth:
//  scratchpad/sprite_src.py. Regenerate with: python sprite_src.py". THAT FILE
//  HAS NEVER EXISTED IN THIS REPOSITORY - `git log --all` over all 77 commits
//  found no trace of it, scratchpad/ is not in the tree and is not even in
//  .gitignore, and ui/petfx.cpp:13 and ui/xbm_mirror.h:19 both already said so
//  out loud. tools/check.sh had no rule for this file either, so 9.4 KB of art
//  was labelled generated, its generator was unreachable, and nothing checked it
//  in either direction. An instruction that cannot be followed is worse than no
//  instruction: it tells the next reader their edit will be overwritten, when in
//  fact nothing ever will. P9-C1 wrote the generator that was missing and P9-C3
//  moved the art onto it.
//
//  Format: XBM - see data/sprite_types.h, which owns the stride/bit-order/frame
//  contract and the two size-guard macros. Feed straight to
//  u8g2.drawXBM(x, y, w, h, bits).
//  All arrays are `inline constexpr` so the linker keeps ONE copy in .rodata
//  (flash) no matter how many translation units include this header.
// -----------------------------------------------------------------------------
#ifndef NT_SPRITES_H
#define NT_SPRITES_H

#include <stdint.h>
#include "sprite_types.h"
#include "sprites_bugs.h"   // THE ATLAS. Generated from tools/sprites/*.txt.
#include "../core/nt_types.h"

// THE ART REVISION, DERIVED (P9-C3). It was `#define SPRITE_REV 1` with a
// comment telling a human to bump it on any art change, and a number a human is
// supposed to bump is a number that does not get bumped - this file's own
// SPRITE_DATA_BYTES was wrong by 144 B for two phases for exactly that reason.
// ER_SPRITE_ART_HASH is FNV-1a over every emitted byte, every set's dimensions,
// the set ORDER and the eye bands, folded to 16 bits by tools/gen_sprites.py, so
// it moves when the art moves and it cannot be forgotten. The DIAG page
// (ui.cpp) prints it; the browser caches sprite blobs by (id, rev).
#define SPRITE_REV ((unsigned)ER_SPRITE_ART_HASH)

// SpriteRef, SpriteSet, spr_xbm_bytes(), spr_set_bytes() and the two size-guard
// macros moved to data/sprite_types.h at P9-C1, unchanged. They are the format,
// not the art, and the generated atlas has to assert its own rows without
// including this file.

// Body pose. IDLE always exists; the others fall back to IDLE when the stage
// has no distinct art (see sprite_set_id()).
enum SpritePose : uint8_t {
  POSE_IDLE = 0,
  POSE_SLEEP,
  POSE_SICK,
  POSE_EAT,
  POSE_COUNT
};

enum IconId : uint8_t {
  ICO_MEAL,
  ICO_SNACK,
  ICO_SOAP,
  ICO_LAMP,
  ICO_BALL,
  ICO_MED,
  ICO_POOP,
  ICO_HEART,
  ICO_SKULL,
  ICO_WIFI,
  ICO_BLE,
  ICO_BATTERY,
  ICO_EGG,
  ICO_DNA,
  ICO_GEAR,
  ICO_HOME,
  ICO_COUNT
};

enum MiniIconId : uint8_t {
  MIC_HUNGER,
  MIC_HAPPY,
  MIC_ENERGY,
  MIC_HYGIENE,
  MIC_HEALTH,
  MIC_BOND,
  MIC_POOP,
  MIC_SICK,
  MIC_SLEEP,
  MIC_WIFI,
  MIC_BLE,
  MIC_ALERT,
  MIC_CLOCK,
  MIC_MUTE,
  MIC_LOCK,
  MIC_SUN,
  MIC_MOON,
  MIC_ARROW_L,
  MIC_ARROW_R,
  MIC_OK,
  MIC_NO,
  MIC_COUNT
};

enum EmoteId : uint8_t {
  EMO_ZZZ,
  EMO_HEART,
  EMO_NOTE,
  EMO_SWEAT,
  EMO_TEAR,
  EMO_ANGER,
  EMO_EXCLAM,
  EMO_QUESTION,
  EMO_GERM,
  EMO_BOWL,
  EMO_BUBBLES,
  EMO_SPARK,
  EMO_COUNT
};

// THE SET IDS MOVED. `enum SpriteSetId` and its 38 tags lived here; the atlas
// is now data/sprites_bugs.h's `enum BugSpriteSetId`, generated from
// tools/sprites/atlas.txt, and P9-C3 deleted the hand-written one rather than
// leaving a second name for the same slots. The order is still a contract and
// atlas.txt is still where it is written down.

// -----------------------------------------------------------------------------
//  PIXEL DATA
// -----------------------------------------------------------------------------

// 12x12 icons  16 x 12x12  (384 B)
inline constexpr uint8_t spr_icon12[] = {
  0x24, 0x01, 0x92, 0x00, 0x24, 0x01, 0x00, 0x00, 0xF0, 0x00, 0xFC, 0x03, 0xFE, 0x07, 0xFF, 0x0F,
  0xFF, 0x0F, 0x00, 0x00, 0xFF, 0x0F, 0xFE, 0x07, 0xF8, 0x00, 0xFC, 0x01, 0xFE, 0x03, 0xF6, 0x06,
  0xFE, 0x03, 0xFC, 0x01, 0xF8, 0x00, 0x20, 0x00, 0x20, 0x00, 0x20, 0x00, 0x70, 0x00, 0x00, 0x00,
  0x84, 0x01, 0x4A, 0x02, 0x84, 0x01, 0x00, 0x00, 0xFC, 0x03, 0xFE, 0x07, 0xFB, 0x0F, 0xFF, 0x0F,
  0xFF, 0x0F, 0xFE, 0x07, 0xFC, 0x03, 0x00, 0x00, 0xF0, 0x00, 0x0C, 0x03, 0x06, 0x06, 0x06, 0x06,
  0x06, 0x06, 0x06, 0x06, 0x0C, 0x03, 0xF8, 0x01, 0xF0, 0x00, 0xF8, 0x01, 0xF0, 0x00, 0x60, 0x00,
  0xF8, 0x01, 0xFE, 0x07, 0x9B, 0x0D, 0x99, 0x09, 0x0F, 0x0F, 0x61, 0x08, 0x61, 0x08, 0x0F, 0x0F,
  0x99, 0x09, 0x9B, 0x0D, 0xFE, 0x07, 0xF8, 0x01, 0x80, 0x07, 0xC0, 0x0F, 0xE0, 0x0E, 0x70, 0x0E,
  0x38, 0x07, 0x9C, 0x03, 0xCE, 0x01, 0xE7, 0x00, 0x77, 0x00, 0x3F, 0x00, 0x1E, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x30, 0x00, 0x78, 0x00, 0xFC, 0x00, 0x86, 0x01, 0xFE, 0x01, 0xFF, 0x03, 0x79, 0x06,
  0xFF, 0x0F, 0x99, 0x09, 0xFF, 0x0F, 0x00, 0x00, 0x00, 0x00, 0x8E, 0x03, 0xDF, 0x07, 0xFF, 0x07,
  0xFF, 0x07, 0xFF, 0x07, 0xFE, 0x03, 0xFC, 0x01, 0xF8, 0x00, 0x70, 0x00, 0x20, 0x00, 0x00, 0x00,
  0xF8, 0x01, 0xFE, 0x07, 0xFF, 0x0F, 0xFF, 0x0F, 0x63, 0x0C, 0x63, 0x0C, 0xFF, 0x0F, 0x9F, 0x0F,
  0xFE, 0x07, 0xFC, 0x03, 0xB4, 0x05, 0xFC, 0x03, 0x00, 0x00, 0xFC, 0x03, 0x02, 0x04, 0xF9, 0x09,
  0x08, 0x01, 0xF0, 0x00, 0x00, 0x00, 0x60, 0x00, 0xF0, 0x00, 0xF0, 0x00, 0x60, 0x00, 0x00, 0x00,
  0x30, 0x00, 0x70, 0x00, 0xF0, 0x00, 0xB4, 0x01, 0x78, 0x03, 0xF0, 0x03, 0xF0, 0x03, 0x78, 0x03,
  0xB4, 0x01, 0xF0, 0x00, 0x70, 0x00, 0x30, 0x00, 0x00, 0x00, 0xF0, 0x00, 0xFF, 0x0F, 0x01, 0x08,
  0x6D, 0x0B, 0x6D, 0x0B, 0x6D, 0x0B, 0x6D, 0x0B, 0x6D, 0x0B, 0x01, 0x08, 0xFF, 0x0F, 0x00, 0x00,
  0xF0, 0x00, 0xFC, 0x03, 0xFE, 0x07, 0xFF, 0x0F, 0xFF, 0x0F, 0xFF, 0x0F, 0x6D, 0x0B, 0xDB, 0x06,
  0xFF, 0x0F, 0xFE, 0x07, 0xFC, 0x03, 0xF0, 0x00, 0x01, 0x04, 0x06, 0x03, 0xFC, 0x01, 0x88, 0x00,
  0x04, 0x01, 0x02, 0x02, 0x01, 0x04, 0x02, 0x02, 0xFC, 0x01, 0x88, 0x00, 0x04, 0x01, 0x02, 0x02,
  0x08, 0x01, 0x9C, 0x03, 0xFE, 0x0F, 0xFF, 0x0F, 0x0F, 0x0F, 0x07, 0x0E, 0x07, 0x0E, 0x0F, 0x0F,
  0xFF, 0x0F, 0xFE, 0x0F, 0x9C, 0x03, 0x08, 0x01, 0x60, 0x00, 0xF0, 0x00, 0xF8, 0x01, 0xFC, 0x03,
  0xFE, 0x07, 0xFF, 0x0F, 0xFC, 0x03, 0x04, 0x02, 0xF4, 0x02, 0xF4, 0x02, 0xF4, 0x02, 0xFC, 0x03,
};
// 384 B. Tied to ICO_COUNT, not to a literal: sprite_icon() indexes this atlas
// with any id < ICO_COUNT, so an icon added to the enum without art (or art
// added without an enum entry) must be a compile error, not an OOB drawXBM.
static_assert(sizeof(spr_icon12) == (size_t)ICO_COUNT * spr_xbm_bytes(12, 12),
              "spr_icon12 size vs ICO_COUNT");

// 8x8 mini icons  21 x 8x8  (168 B)
inline constexpr uint8_t spr_mini8[] = {
  0x25, 0x25, 0x27, 0x62, 0x22, 0x22, 0x22, 0x00, 0x3C, 0x7E, 0xDB, 0xFF, 0xBD, 0xC3, 0x7E, 0x3C,
  0x30, 0x18, 0x0C, 0x3E, 0x18, 0x0C, 0x06, 0x00, 0x08, 0x1C, 0x3E, 0x7F, 0x7F, 0x7F, 0x3E, 0x1C,
  0x3C, 0x3C, 0xFF, 0xFF, 0xFF, 0xFF, 0x3C, 0x3C, 0x66, 0xFF, 0xFF, 0xFF, 0x7E, 0x3C, 0x18, 0x00,
  0x00, 0x0C, 0x1E, 0x3F, 0x59, 0xFF, 0xAD, 0xFF, 0x24, 0x7E, 0xDB, 0xFF, 0xBD, 0x7E, 0x24, 0x00,
  0x3F, 0x30, 0x18, 0x0C, 0x06, 0x3F, 0x00, 0x00, 0x3E, 0x41, 0x1C, 0x22, 0x08, 0x1C, 0x1C, 0x00,
  0x08, 0x18, 0x2A, 0x1C, 0x1C, 0x2A, 0x18, 0x08, 0x1C, 0x1C, 0x1C, 0x1C, 0x1C, 0x00, 0x1C, 0x1C,
  0x3C, 0x42, 0x89, 0x89, 0xB9, 0x81, 0x42, 0x3C, 0x98, 0x5C, 0x3F, 0x1F, 0x1F, 0x3F, 0x5C, 0x98,
  0x3C, 0x42, 0x42, 0xFF, 0xE7, 0xE7, 0xFF, 0x00, 0x29, 0x3E, 0x7F, 0x5D, 0x7F, 0x3E, 0x94, 0x00,
  0x1C, 0x06, 0x07, 0x07, 0x07, 0x06, 0x1C, 0x00, 0x10, 0x18, 0x1C, 0x1E, 0x1C, 0x18, 0x10, 0x00,
  0x08, 0x18, 0x38, 0x78, 0x38, 0x18, 0x08, 0x00, 0xC0, 0x60, 0x31, 0x1B, 0x1E, 0x0C, 0x00, 0x00,
  0xC3, 0xE7, 0x7E, 0x3C, 0x3C, 0x7E, 0xE7, 0xC3,
};
// 168 B, indexed by sprite_mini() with any id < MIC_COUNT.
static_assert(sizeof(spr_mini8) == (size_t)MIC_COUNT * spr_xbm_bytes(8, 8),
              "spr_mini8 size vs MIC_COUNT");

// NO MOOD FACES (P4-C6). `spr_mood12` was 6 x 12x12 = 144 B of authored art
// reached only by sprite_mood_face(), whose last caller went away at P2-C11b
// (b450b11). At this commit the accessor had ZERO references in Errata/src
// and in tests/, its one remaining consumer BugView.mood_face was written
// by ui.cpp every frame and read by no screen, and riscv32-elf-nm confirms the
// array was dropped from every linked ELF by --gc-sections - so it cost 0 B and
// proved nothing. The chain is deleted whole rather than left as a fourth
// pet_view_fill(). RECOVER THE ART with
// `git show 250f73e:Pebblebol/src/data/sprites.h` if the P10 art pass designs a
// screen with a mood badge on it; the enum (Mood, core/nt_types.h), the ladder
// (pet_mood_index) and the Spanish mood words (STR_MOOD_*) are all still here
// and still live, so only the pixels would have to come back. THE SIZE GUARD
// WENT WITH THE ARRAY, not ahead of it: `static_assert(sizeof(spr_mood12) ==
// MOOD_COUNT * spr_xbm_bytes(12,12))` measured data that no longer exists. No
// assertion about anything still in this file was weakened.


// species badges  13 x 12x12  (312 B)
// The count lives here, next to the art it measures; sprite_species_badge()
// clamps to it (12..15 all render the last, UNKNOWN, badge).
#define SPRITE_BADGE_COUNT 13
inline constexpr uint8_t spr_badge12[] = {
  0xF0, 0x00, 0xFC, 0x03, 0xFE, 0x07, 0xFF, 0x0F, 0xFB, 0x0D, 0xFB, 0x0D, 0xFF, 0x0F, 0xFF, 0x0F,
  0xFE, 0x07, 0xFC, 0x03, 0x0C, 0x03, 0x0C, 0x03, 0x00, 0x00, 0x02, 0x04, 0x04, 0x02, 0xF8, 0x01,
  0xFC, 0x03, 0xFE, 0x07, 0xFF, 0x0F, 0xFF, 0x0F, 0xFE, 0x07, 0xFC, 0x03, 0x0A, 0x05, 0x0A, 0x05,
  0x24, 0x01, 0x6C, 0x03, 0xF8, 0x01, 0xFC, 0x03, 0xFE, 0x07, 0xF7, 0x0E, 0xFF, 0x0F, 0xBF, 0x0F,
  0xFE, 0x0D, 0xFC, 0x03, 0x98, 0x01, 0x98, 0x01, 0x06, 0x06, 0x0E, 0x07, 0x3E, 0x07, 0xFE, 0x07,
  0xFF, 0x0F, 0xFB, 0x0D, 0xFB, 0x0D, 0xFF, 0x0F, 0xFD, 0x0B, 0xFF, 0x0F, 0x04, 0x02, 0x0C, 0x07,
  0xF8, 0x01, 0xFE, 0x07, 0xFF, 0x0F, 0xFB, 0x0E, 0xFF, 0x0F, 0xFE, 0x07, 0xF8, 0x01, 0xF0, 0x00,
  0x90, 0x00, 0x90, 0x00, 0xF8, 0x01, 0xF8, 0x01, 0xF0, 0x00, 0xF3, 0x0C, 0xF5, 0x0A, 0xF5, 0x0A,
  0xF5, 0x0A, 0xF7, 0x0E, 0xF0, 0x00, 0xF6, 0x06, 0xF0, 0x00, 0xF0, 0x00, 0xFC, 0x03, 0xFC, 0x03,
  0x00, 0x00, 0xF0, 0x04, 0xFC, 0x0D, 0xFE, 0x0B, 0xF7, 0x07, 0xFB, 0x07, 0xF7, 0x0B, 0xFE, 0x0B,
  0xFC, 0x0D, 0xF0, 0x04, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0xF0, 0x00, 0xFE, 0x07, 0x02, 0x04,
  0x9A, 0x05, 0x9A, 0x05, 0x02, 0x04, 0xFA, 0x05, 0xFE, 0x07, 0x0C, 0x03, 0x0C, 0x03, 0x00, 0x00,
  0xF8, 0x01, 0xFE, 0x07, 0xFF, 0x0F, 0x7B, 0x0F, 0x7B, 0x0F, 0xFF, 0x0F, 0xB7, 0x0F, 0xFF, 0x0F,
  0xFF, 0x0F, 0xDB, 0x0E, 0x49, 0x0A, 0x00, 0x00, 0xCC, 0x00, 0xCC, 0x00, 0xCC, 0x00, 0xFE, 0x01,
  0xFF, 0x03, 0x7B, 0x07, 0xFF, 0x03, 0xFD, 0x02, 0xFF, 0x03, 0xFE, 0x01, 0xCC, 0x00, 0xCE, 0x01,
  0x03, 0x0C, 0x06, 0x06, 0xFC, 0x03, 0xFE, 0x07, 0xFB, 0x0D, 0xFF, 0x0F, 0xDF, 0x0F, 0xFF, 0x0F,
  0x9E, 0x07, 0x0C, 0x03, 0x0E, 0x07, 0x00, 0x00, 0xF8, 0x01, 0xFE, 0x07, 0xFF, 0x0F, 0xFB, 0x0D,
  0xFF, 0x0F, 0xFE, 0x07, 0xFC, 0x03, 0x6A, 0x05, 0x69, 0x09, 0x69, 0x09, 0x0A, 0x05, 0x0A, 0x05,
  0xF8, 0x01, 0xFE, 0x07, 0x03, 0x0F, 0x00, 0x0F, 0x80, 0x07, 0xC0, 0x03, 0xE0, 0x01, 0x60, 0x00,
  0x00, 0x00, 0x60, 0x00, 0x60, 0x00, 0x00, 0x00,
};
static_assert(sizeof(spr_badge12) == (size_t)SPRITE_BADGE_COUNT * spr_xbm_bytes(12, 12),
              "spr_badge12 size vs SPRITE_BADGE_COUNT");

inline constexpr uint8_t spr_emo_zzz[] = {  // 16x10
  0x00, 0xFC, 0x00, 0x44, 0x00, 0x22, 0x00, 0x11, 0x80, 0x1F, 0x1E, 0x00, 0x10, 0x00, 0x0C, 0x00,
  0x02, 0x00, 0x1E, 0x00,
};
inline constexpr uint8_t spr_emo_heart[] = {  // 12x10
  0x8E, 0x03, 0xDF, 0x07, 0xFF, 0x07, 0xFF, 0x07, 0xFF, 0x07, 0xFE, 0x03, 0xFC, 0x01, 0xF8, 0x00,
  0x70, 0x00, 0x20, 0x00,
};
inline constexpr uint8_t spr_emo_note[] = {  // 8x10
  0xF0, 0x90, 0x90, 0x90, 0x90, 0x90, 0x9E, 0xF3, 0x63, 0x06,
};
inline constexpr uint8_t spr_emo_sweat[] = {  // 6x8
  0x0C, 0x0C, 0x1E, 0x1E, 0x3F, 0x3F, 0x1E, 0x0C,
};
inline constexpr uint8_t spr_emo_tear[] = {  // 5x7
  0x04, 0x04, 0x0E, 0x0E, 0x1F, 0x1F, 0x0E,
};
inline constexpr uint8_t spr_emo_anger[] = {  // 8x8
  0x81, 0xC3, 0x66, 0x3C, 0x3C, 0x66, 0xC3, 0x81,
};
inline constexpr uint8_t spr_emo_exclam[] = {  // 5x11
  0x0E, 0x0E, 0x0E, 0x0E, 0x0E, 0x0E, 0x04, 0x00, 0x0E, 0x0E, 0x0E,
};
inline constexpr uint8_t spr_emo_question[] = {  // 8x11
  0x3C, 0x7E, 0xC3, 0xC3, 0x60, 0x30, 0x18, 0x18, 0x00, 0x18, 0x18,
};
inline constexpr uint8_t spr_emo_germ[] = {  // 12x12
  0x64, 0x02, 0x02, 0x04, 0xF9, 0x09, 0xFC, 0x03, 0xF6, 0x06, 0xFF, 0x07, 0xFF, 0x07, 0xF6, 0x06,
  0xFC, 0x03, 0xF9, 0x09, 0x02, 0x04, 0x64, 0x02,
};
inline constexpr uint8_t spr_emo_bowl[] = {  // 14x8
  0x24, 0x02, 0x12, 0x01, 0x00, 0x00, 0xFF, 0x3F, 0xFE, 0x1F, 0xFE, 0x1F, 0xFC, 0x0F, 0xF8, 0x07,
};
inline constexpr uint8_t spr_emo_bubbles[] = {  // 12x12
  0x0C, 0x00, 0x12, 0x00, 0xCC, 0x03, 0x20, 0x04, 0x10, 0x08, 0x10, 0x08, 0x20, 0x04, 0xC0, 0x03,
  0x18, 0x00, 0x24, 0x00, 0x24, 0x00, 0x18, 0x00,
};
inline constexpr uint8_t spr_emo_spark[] = {  // 8x8
  0x18, 0x18, 0x99, 0x7E, 0x7E, 0x99, 0x18, 0x18,
};



// -----------------------------------------------------------------------------
//  TABLES
// -----------------------------------------------------------------------------

// SPRITE_SETS MOVED TOO. Its 38 rows are ER_SPRITE_SETS in
// data/sprites_bugs.h, emitted with an NT_SPR_SET_FITS beside every one of
// them; the run of NT_SPR_SET_FITS lines that used to sit below this file's
// emote guards went with the table it guarded.

inline constexpr SpriteRef SPRITE_EMOTES[EMO_COUNT] = {
  { spr_emo_zzz, 16, 10 },
  { spr_emo_heart, 12, 10 },
  { spr_emo_note, 8, 10 },
  { spr_emo_sweat, 6, 8 },
  { spr_emo_tear, 5, 7 },
  { spr_emo_anger, 8, 8 },
  { spr_emo_exclam, 5, 11 },
  { spr_emo_question, 8, 11 },
  { spr_emo_germ, 12, 12 },
  { spr_emo_bowl, 14, 8 },
  { spr_emo_bubbles, 12, 12 },
  { spr_emo_spark, 8, 8 },
};


// -----------------------------------------------------------------------------
//  ATLAS / TABLE SIZE GUARDS
//
//  Both tables above carry a w/h that drawXBM() trusts absolutely: it reads
//  ((w+7)>>3)*h bytes from `bits` with no bound of its own. These asserts tie
//  every array to the dimensions its own table entry advertises, so an art edit
//  that changes a bitmap without updating the table (or the other way round) is
//  a compile error instead of a silent out-of-bounds read into the neighbouring
//  sprite. The macros live in data/sprite_types.h.
//
//  UNTIL P9-C1 ONLY THE EMOTE HALF EXISTED. The 38 SpriteSet rows were guarded
//  by per-array `sizeof(spr_x) == <literal>` asserts, which compare an array to
//  a number and say nothing about what the TABLE claims - so
//  `{ spr_adult_bolota, 48, 40, 2 }` compiled clean and read 80 bytes past the
//  end of a 400-byte array. The literal asserts stay (they pin the art size
//  itself); NT_SPR_SET_FITS is what ties them to the table.
// -----------------------------------------------------------------------------
NT_SPR_REF_FITS(spr_emo_zzz,       SPRITE_EMOTES, EMO_ZZZ);
NT_SPR_REF_FITS(spr_emo_heart,     SPRITE_EMOTES, EMO_HEART);
NT_SPR_REF_FITS(spr_emo_note,      SPRITE_EMOTES, EMO_NOTE);
NT_SPR_REF_FITS(spr_emo_sweat,     SPRITE_EMOTES, EMO_SWEAT);
NT_SPR_REF_FITS(spr_emo_tear,      SPRITE_EMOTES, EMO_TEAR);
NT_SPR_REF_FITS(spr_emo_anger,     SPRITE_EMOTES, EMO_ANGER);
NT_SPR_REF_FITS(spr_emo_exclam,    SPRITE_EMOTES, EMO_EXCLAM);
NT_SPR_REF_FITS(spr_emo_question,  SPRITE_EMOTES, EMO_QUESTION);
NT_SPR_REF_FITS(spr_emo_germ,      SPRITE_EMOTES, EMO_GERM);
NT_SPR_REF_FITS(spr_emo_bowl,      SPRITE_EMOTES, EMO_BOWL);
NT_SPR_REF_FITS(spr_emo_bubbles,   SPRITE_EMOTES, EMO_BUBBLES);
NT_SPR_REF_FITS(spr_emo_spark,     SPRITE_EMOTES, EMO_SPARK);



// -----------------------------------------------------------------------------
//  THE ART BUDGET - MEASURED BY THE COMPILER, NOT TYPED BY A HUMAN
//
//  THIS USED TO BE `#define SPRITE_DATA_BYTES 10623` GUARDED BY
//  `static_assert(SPRITE_DATA_BYTES <= 24576)`, WHICH IS A COMPARISON OF TWO
//  LITERALS. It could not fail from an art change, and it had already failed to:
//  the number was correct at d21f20f^ and P4-C6 then deleted spr_mood12 (6 x
//  12x12 = 144 B) without touching it, so it over-stated the atlas by exactly
//  144 B for two phases while the assert stayed green. P9-C1 made it walk the
//  real arrays through the real tables. This file now owns TWO tables' worth of
//  art - the generated atlas it includes, and the icons/mini-icons/badges/emotes
//  that were never part of the swap - and counts both.
//
//  THE 24,576 CEILING IS GONE, AND THAT IS THE POINT OF THIS CHUNK. It was a
//  TRANSITION allowance sized for the one moment both rosters were in the tree
//  at once (peak 10,479 + 8,640 = 19,119 B). Both rosters are no longer in the
//  tree: the 36 legacy body and pose sets are deleted. An allowance left
//  standing after the thing it allowed for is a budget that has stopped meaning
//  anything, so the number below is the END STATE plus a stated margin:
//
//      generated atlas   9,216 B   2 eggs + SLEEP + SICK + 60 bodies, all
//                                  24x24x2 at 144 B (data/sprites_bugs.h,
//                                  ER_SPRITE_DATA_BYTES_DECLARED)
//      survivors         1,031 B   spr_icon12 384 + spr_mini8 168 +
//                                  spr_badge12 312 + the 12 emotes 167
//                                  (CORRECTED AT P9-C6: this line read "96" and
//                                  "239", which are wrong by +/-72 B and cancel,
//                                  so the total was right and neither term was.
//                                  spr_mini8 is MIC_COUNT = 21 icons x 8 B; 96
//                                  would be twelve. The test below now asserts
//                                  the four TERMS and not only their sum, which
//                                  is what let two wrong numbers sit next to a
//                                  passing assertion in three files.)
//      END STATE        10,247 B   = SPRITE_DATA_BYTES_DECLARED below
//      margin            1,017 B   SEVEN more 24x24x2 sets (1,008 B): one more
//                                  three-stage family and four effect sets,
//                                  which is what P9-C5's corruption glitch and
//                                  P10's animation pass could plausibly want
//      MAX              11,264 B   the two, rounded up to 11 KiB
//
//  That is 0.70 % of the 1,600,000 B RELEASE flash cap and 4.1 % of the 273,600 B
//  the release variant had spare at 37511d5. Both halves name the same variant
//  now: the sentence used to quote 0.47 % of GATE_FLASH_MAX (2,400,000), which
//  check.sh polices on the BASELINE build, beside a number derived from
//  GATE_RELEASE_FLASH_MAX - the two-caps confusion docs/decisions.md already has
//  a paragraph correcting. A roster that grows past it is not a
//  budget failure to absorb, it is a re-plan: 21 families would need this number
//  raised and said out loud, which is exactly the conversation 24,576 was
//  swallowing.
// -----------------------------------------------------------------------------
constexpr unsigned sprite_atlas_bytes() {
  unsigned n = pb_sprite_atlas_bytes();
  for (unsigned i = 0; i < (unsigned)EMO_COUNT; ++i)
    n += spr_xbm_bytes(SPRITE_EMOTES[i].w, SPRITE_EMOTES[i].h);
  return n + (unsigned)sizeof(spr_icon12) + (unsigned)sizeof(spr_mini8)
           + (unsigned)sizeof(spr_badge12);
}

#define SPRITE_DATA_BYTES          (sprite_atlas_bytes())
#define SPRITE_DATA_BYTES_DECLARED 10247u
#define SPRITE_DATA_BYTES_MAX      11264u

static_assert(SPRITE_DATA_BYTES == SPRITE_DATA_BYTES_DECLARED,
              "the atlas changed size - re-measure SPRITE_DATA_BYTES_DECLARED "
              "and say so in the commit (tools/check.sh cannot see art)");
static_assert(SPRITE_DATA_BYTES <= SPRITE_DATA_BYTES_MAX,
              "sprite art over the flash budget");

// -----------------------------------------------------------------------------
//  LOOKUP
//
//  EVERYTHING FROM HERE TO THE END OF THE FILE IS HAND-WRITTEN LOGIC, not art.
//  The art is data/sprites_bugs.h, generated from tools/sprites/*.txt.
//
//  WHAT P9-C3 DID TO THIS BLOCK, AND WHAT IT COST.
//
//  ONE BODY PER SPECIES. sprite_design_of() is gone. It folded an art key with
//  `% 8` at BABY and `% 6` at ADULT/SENIOR because the atlas authored 8 baby
//  bodies and 6 adult ones for 36 species; the atlas now authors 60, one per
//  roster id, at ER_SPRITE_BODY_FIRST + (id - 1). `form` IS the art key.
//
//  THE STAGE NO LONGER CHANGES THE BODY, and that is a real deletion, not a
//  refactor. A Bug's silhouette is its species at every stage from BABY to
//  SENIOR. What used to carry growth - blob -> child -> teen -> 40x40 adult ->
//  32x32 senior - is now carried by the ROSTER instead: a family's three
//  species ARE its three stages (species.json `stage` 0/1/2), they evolve into
//  one another, and each has its own drawing. So growth is still on screen; it
//  is on screen once per family instead of five times per pet.
//
//  THE CARE-QUALITY BODY IS DELETED. sprite_form_of() used to read minor_form
//  at CHILD and TEEN to pick SPR_CHILD_GOOD vs SPR_CHILD_POOR - the care
//  quality frozen when the pet grew. One body per species has nowhere to put
//  it: a "descuidado" variant would be a 61st..120th drawing. The parameter is
//  gone from the signature rather than ignored, so every call site had to be
//  visited; tests/test_pet_view.cpp records the deletion and pins the rule that
//  replaced it. Whoever wants care quality back on HOME should draw it with the
//  renderer (a sweat emote, a dulled dither) and not with a second atlas.
//
//  THE POSE QUESTION, ANSWERED. The legacy atlas had SEVEN pose sets - SLEEP at
//  four sizes, SICK and EAT at three. There are now TWO, both 24x24:
//
//    SLEEP  ONE generic body, 144 B. SLEEP is a STATE: pet_pose_of() returns it
//           from the sim, it persists, and HOME has to show it on the STILL
//           path (ui/screen_home.cpp), which is the only body path a host test
//           or a golden can see. Per-species sleepers would be 60 x 144 =
//           8,640 B more and 60 more drawings.
//    SICK   ONE generic body, 144 B, for the same reason: pet_pose_of() returns
//           POSE_SICK from PF_SICK, so it is a state and not a film.
//    EAT    NO ART AT ALL. POSE_EAT is reachable ONLY from actfx_pose() during
//           the two-second feeding film (ui/actfx.cpp); pet_pose_of() never
//           returns it, no golden has ever recorded it, and the renderer
//           already parks EMO_BOWL against the body's measured ink wall and can
//           lean the body with petfx_squash(). So POSE_EAT falls through to the
//           species body and the film carries the pose. COST, stated: the
//           authored "leaning over the bowl" silhouette is gone, and what
//           replaces it lives in ui/actfx.cpp + ui/petfx.cpp, which are
//           device-only translation units no host binary compiles. That is the
//           one place this chunk moves behaviour into a layer the suite cannot
//           see, and it is the pose that was already invisible to it.
//
//  IDENTITY LOSS ON SLEEP AND SICK IS INHERITED, NOT INTRODUCED. The old
//  sprite_set_id() ignored `form` in every pose branch, so a sleeping BABY_GATO,
//  BABY_SETA, BABY_PEZ and BABY_ROBOT were already the same blob. What changed
//  is the count (7 sets -> 2) and the size (24, 28, 32 and 40 px -> 24), not
//  whether a species keeps its face while it sleeps. It does not, and it did
//  not.
// -----------------------------------------------------------------------------

// The half-open window of set ids that are CREATURE BODIES. Everything outside
// it is an egg or a pose, and a species that resolves onto one of those is not
// being drawn - it is being mistaken for furniture. game/species.cpp asserts
// the whole roster against it at compile time and tests/test_content.cpp
// re-checks it at runtime.
#define SPRITE_BODY_FIRST  ((uint8_t)ER_SPRITE_BODY_FIRST)
#define SPRITE_BODY_LAST   ((uint8_t)(ER_SPRITE_BODY_FIRST + ER_SPRITE_BODY_COUNT - 1))
#define SPRITE_SET_COUNT   ((uint8_t)ER_SPRITE_SET_COUNT)

// -----------------------------------------------------------------------------
//  sprite_form_of(art_key, stage) - THE ONLY correct source of `form`.
//
//  `form` is the art key for every stage that has a body, and 0 for an egg
//  (an egg is an egg). `art_key` is ui/pet_art.h's pet_art_key(): the SPECIES
//  row's sprite_id when the Bug has a row, and the genome's species nibble
//  when it has none.
//
//  THE minor_form PARAMETER WENT WITH THE CARE-QUALITY BODIES - see the banner
//  above. It is not ignored, it is absent, so a call site that still had
//  something to say about it is a compile error rather than a silent no-op.
// -----------------------------------------------------------------------------
// data/ may not depend on game/, so this takes the decoded key rather than the
// live view it comes from.
constexpr uint8_t sprite_form_of(uint8_t art_key, Stage stage) {
  return (stage == STAGE_EGG) ? (uint8_t)0 : art_key;
}

// Map a live pet onto an animation set id.
//   stage : enum Stage.
//   form  : sprite_form_of() output - the species' art key.
//   pose  : enum SpritePose. POSE_EAT falls through to the body on purpose.
//
// THE CLAMP IS NOT DECORATION. `form` can reach here from a saved nibble a
// future save format widened, or from a species row a newer build wrote, and an
// unclamped add would index straight past ER_SPRITE_SETS into whatever follows
// it. Out of range falls back to the first body, never past the end.
//
// =============================================================================
//  THE THREE POSE BRANCHES BELOW WERE DECIDED AT P10-C3, NOT LEFT. Read this
//  before changing one of them; each is a different answer for a different
//  reason, and "they are all shared" stopped being true.
//
//  POSE_SLEEP - STILL RETURNS THE SHARED BODY HERE, AND ALMOST NOTHING USES IT.
//  Sleep is DERIVED at draw time since P10-C3: ui/petfx_core.cpp's
//  pf_build_sleep() takes the species' own idle frame, shuts its eyes with the
//  blink's own pf_build_lids(), merges its two topmost ink rows and splays its
//  bottom four, and BOTH of HOME's body paths call it - ui/screen_home.cpp's
//  still one and ui/petfx.cpp's animated one. So a sleeping Bug keeps its
//  silhouette, which on HOME is the only thing distinguishing it from anyone
//  else's, and the change is measured: 13 px on the quietest body in the roster
//  (ESTATIC) against a floor of 10, asserted over all 120 (species, frame) pairs
//  in tests/test_sprite_pipeline.cpp.
//    WHY THE BRANCH SURVIVES ANYWAY: pf_build_sleep() refuses a blank frame or
//  one wider than the cache geometry, and this is what the caller falls back
//  to. No body in today's atlas takes that path - the sweep says so by name -
//  and the 144 B stays because it is the safety net under a derivation, in
//  exactly the spirit of the clamp two lines down. Deleting it would also mean
//  regenerating the atlas and moving ER_SPRITE_BODY_FIRST, which is a re-plan
//  for 144 B.
//
//  POSE_SICK - GENUINELY SHARED, AND THAT IS THE DECISION RATHER THAN THE
//  LEFTOVER. Every cheap derivation is already spoken for or already known bad:
//  the squash is the SLEEP pose and also the landing and the yawn; an erase
//  dither is gene_pattern, and ui/petfx.cpp's PF_PAT_LEVEL banner records that
//  anything at or above level 3 combs a body into a venetian blind; a one-row
//  shear on the upper half is a new shape rule applied to sixty drawings by
//  five hands, and NO INSTRUMENT IN THIS REPOSITORY CAN TELL "slumped" FROM
//  "broken" - only a person can, one body at a time. So SICK keeps the generic
//  body, and the identity loss is real and is being accepted rather than
//  denied. THE OWNER STEP, priced: author twenty family sick bodies (one per
//  family, 20 x 144 = 2,880 B), raise ER_SPRITE_DATA_BYTES_MAX in
//  tools/gen_sprites.py AND SPRITE_DATA_BYTES_MAX above, and review them with
//  `./bin/sprite_dump text NAME`. The atlas has 1,024 B free, so twenty sets do
//  NOT fit and this is a re-plan of both caps, said out loud.
//
//  POSE_EAT - NOT A GAP, AND THE TREE ALREADY PROVED IT. It falls through to
//  the species body on purpose and the FILM carries the pose: ui/actfx.cpp
//  lunges the whole silhouette at the bowl, dips it on the bite and parks the
//  bowl against the body's measured ink wall. tests/test_screens.cpp pins
//  eat_diff == 0 on HOME with the comment "so 'we dropped it' cannot decay into
//  'we forgot it'". P10-C3 looked at it again and changed nothing.
// =============================================================================
constexpr uint8_t sprite_set_id(uint8_t stage, uint8_t form, uint8_t pose) {
  if (stage == (uint8_t)STAGE_EGG) return (uint8_t)BUGSPR_EGG_IDLE;
  if (pose  == (uint8_t)POSE_SLEEP) return (uint8_t)BUGSPR_SLEEP;
  if (pose  == (uint8_t)POSE_SICK)  return (uint8_t)BUGSPR_SICK;
  return (uint8_t)(ER_SPRITE_BODY_FIRST
                   + (form < (uint8_t)ER_SPRITE_BODY_COUNT ? form : (uint8_t)0));
}

inline SpriteSet sprite_set(uint8_t id) {
  if (id >= (uint8_t)ER_SPRITE_SET_COUNT) id = (uint8_t)BUGSPR_EGG_IDLE;
  return ER_SPRITE_SETS[id];
}

inline SpriteRef sprite_frame(uint8_t id, uint8_t frame) {
  const SpriteSet s = sprite_set(id);
  // `stride` here is BYTES PER FRAME, not the row stride - the two differ and
  // pf_stride(w) three files away means the other one.
  const uint16_t stride = (uint16_t)(((s.w + 7u) >> 3) * s.h);
  if (frame >= s.frames) frame = (uint8_t)(frame % s.frames);
  SpriteRef r = { s.bits + (uint32_t)stride * frame, s.w, s.h };
  return r;
}

// Pose-aware body lookup.
inline SpriteRef sprite_lookup_pose(uint8_t stage, uint8_t form,
                                    uint8_t pose, uint8_t frame) {
  return sprite_frame(sprite_set_id(stage, form, pose), frame);
}

// The blink band for one set and frame, in UNMIRRORED sprite space. Generated
// beside the pixels; { 255, 0, 0, 0 } means this body does not blink.
inline SpriteEyeBand sprite_eyes(uint8_t id, uint8_t frame) {
  if (id >= (uint8_t)ER_SPRITE_SET_COUNT) id = (uint8_t)BUGSPR_EGG_IDLE;
  if (frame > 1u) frame = (uint8_t)(frame & 1u);
  return ER_SPRITE_EYES[id][frame];
}

inline SpriteRef sprite_egg(uint8_t phase, uint8_t frame) {
  return sprite_frame(phase ? (uint8_t)BUGSPR_EGG_CRACK : (uint8_t)BUGSPR_EGG_IDLE, frame);
}

inline SpriteRef sprite_icon(uint8_t id) {
  if (id >= ICO_COUNT) id = 0;
  SpriteRef r = { spr_icon12 + (uint16_t)id * 24u, 12, 12 };
  return r;
}

inline SpriteRef sprite_mini(uint8_t id) {
  if (id >= MIC_COUNT) id = 0;
  SpriteRef r = { spr_mini8 + (uint16_t)id * 8u, 8, 8 };
  return r;
}

// Indexed by the species gene; 12..15 render the UNKNOWN badge.
// SPRITE_BADGE_COUNT is defined next to spr_badge12, with its size guard.
inline SpriteRef sprite_species_badge(uint8_t species) {
  if (species >= SPRITE_BADGE_COUNT) species = SPRITE_BADGE_COUNT - 1;
  SpriteRef r = { spr_badge12 + (uint16_t)species * 24u, 12, 12 };
  return r;
}

inline SpriteRef sprite_emote(uint8_t id) {
  if (id >= EMO_COUNT) id = 0;
  return SPRITE_EMOTES[id];
}

// Nominal draw origin that centres a body sprite inside the sprite area.
inline uint8_t sprite_center_x(uint8_t w) { return (uint8_t)((OLED_W - w) / 2); }
inline uint8_t sprite_center_y(uint8_t h) {
  return (uint8_t)(SPRITE_AREA_Y + (SPRITE_AREA_H > h ? (SPRITE_AREA_H - h) / 2 : 0));
}

#endif  // NT_SPRITES_H
