#!/usr/bin/env bash
# tools/fetch_u8g2.sh - re-vendor the slice of U8g2 the host screen capture needs.
#
# WHY ANY OF THIS IS VENDORED. tests/tools/screen_shot.cpp draws the panel with
# the SAME font code and the SAME glyph bytes the firmware links, because a
# picture of the UI drawn with different fonts is not a picture of the UI. The
# host test build has no Arduino include path at all (tests/Makefile), so the
# library cannot be reached the way the firmware reaches it.
#
# WHY A SLICE AND NOT THE LIBRARY. csrc/u8g2_fonts.c alone is 37 MB - every
# font U8g2 ships. Pebblebol uses five, named in Pebblebol/src/ui/render.h, and
# they come to 18 KB. The extractor below takes those five and nothing else.
#
# THE VERSION IS NOT A CHOICE. It must equal the one .github/workflows/ci.yml
# installs for the firmware build, or the capture and the panel drift apart
# silently - which is the whole class of bug this tool exists to end.
set -euo pipefail

VERSION=2.35.30
BASE="https://raw.githubusercontent.com/olikraus/u8g2/${VERSION}/csrc"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$ROOT/tests/vendor/u8g2"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

ci_version="$(grep -oE 'U8g2@[0-9.]+' "$ROOT/.github/workflows/ci.yml" | head -1 | cut -d@ -f2 || true)"
if [ -n "$ci_version" ] && [ "$ci_version" != "$VERSION" ]; then
  echo "fetch_u8g2: CI installs U8g2@$ci_version but this script pins $VERSION" >&2
  echo "            Change both together or the capture stops matching the panel." >&2
  exit 1
fi

mkdir -p "$DST"

# Verbatim: the headers, the glyph decoder, and the UTF-8 state machine the
# device's drawUTF8() runs.
for f in u8g2.h u8x8.h u8g2_font.c u8x8_8x8.c; do
  echo "  fetching $f"
  curl -sSfL -o "$TMP/$f" "$BASE/$f"
  cp "$TMP/$f" "$DST/$f"
done

echo "  fetching u8g2_fonts.c (37 MB, five fonts kept)"
curl -sSfL -o "$TMP/u8g2_fonts.c" "$BASE/u8g2_fonts.c"

python3 - "$TMP/u8g2_fonts.c" "$DST/u8g2_fonts_pebblebol.c" "$VERSION" <<'PY'
import re, sys, pathlib

src_path, dst_path, version = sys.argv[1], sys.argv[2], sys.argv[3]
src = pathlib.Path(src_path).read_text(encoding="latin-1")

# Pebblebol/src/ui/render.h, the five verified on the panel and nothing else.
WANT = ["u8g2_font_5x8_tf", "u8g2_font_6x10_tf", "u8g2_font_t0_11b_tf",
        "u8g2_font_4x6_tr", "u8g2_font_logisoso16_tn"]

def end_of_decl(s, start):
    """The first ';' at top level. U8g2 stores a font as an escaped string
    literal, and those literals contain semicolons - taking the first ';' by
    index cuts the array in half and the result does not compile."""
    i, in_str, esc = start, False, False
    while i < len(s):
        c = s[i]
        if in_str:
            if esc: esc = False
            elif c == "\\": esc = True
            elif c == '"': in_str = False
        elif c == '"': in_str = True
        elif c == ';': return i
        i += 1
    raise SystemExit("fetch_u8g2: unterminated font declaration")

out = [
    "// GENERATED by tools/fetch_u8g2.sh - DO NOT HAND EDIT.\n"
    f"// The five fonts Pebblebol/src/ui/render.h names, cut verbatim out of\n"
    f"// U8g2 {version} csrc/u8g2_fonts.c. Byte-identical to what the firmware links.\n"
    '#include "u8g2.h"\n'
]
for name in WANT:
    m = re.search(rf"^const uint8_t {name}\[\d*\][^=]*=", src, re.M)
    if not m:
        raise SystemExit(f"fetch_u8g2: {name} not found in u8g2_fonts.c")
    out.append(src[m.start():end_of_decl(src, m.end()) + 1])

pathlib.Path(dst_path).write_text("\n\n".join(out) + "\n", encoding="latin-1")
print(f"  kept {len(WANT)} fonts, {pathlib.Path(dst_path).stat().st_size} bytes")
PY

( cd "$DST" && sha256sum u8g2.h u8x8.h u8g2_font.c u8x8_8x8.c u8g2_fonts_pebblebol.c \
    > SHA256SUMS )
echo "U8g2 $VERSION vendored into tests/vendor/u8g2 (see SHA256SUMS)"
